### ISSUE TITLE
Project Link

### ISSUE THREAD

**Issue by hunter4466** [hunter4466/js-capstone-proj-kanban-board#21]
https://github.com/hunter4466/js-capstone-proj-kanban-board/projects/2

Two people working on this project:
 -Carlos Ospina
 -Mario Chois

**Comment by Dipeshtwis** [comment]
# Status: Approved ✔️

## Hi @hunter4466 &  @carloso0114, 

Good job on implementing all the checklists. Well Done.
Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

**You may close this issue and merge the changes**

  
**Keep being awesome devs and good luck with your next milestone!**
---------

Cheers and Happy coding!👏👏👏
Feel free to leave any questions or comments in the issue thread if something is not 100% clear.
_**Dipesh Kumar**_

--------

_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project(check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
